# Generated by Django 5.0 on 2024-02-23 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_rename_slug_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='img',
            field=models.FileField(blank=True, upload_to='static/assets/img/'),
        ),
    ]
